# This is a basic workflow to verify incoming PRs with just one single machine (openvario-57-lvds)
name: Build images

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
    #branches: [ main ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build_Images:
    name: Build images for release

    # The type of runner that the job will run on
    #runs-on: ubuntu-20.04
    runs-on: self-hosted
    #container:
    #  image: ghcr.io/openvario/ovbuild-container:main
    #  #volumes:
    # #  - $(pwd):/workdir:/workdir


    # Matrix Run: Test all combinations
    strategy:
      matrix:
        #MACHINE: [openvario-57-lvds, openvario-7-PQ070, openvario-7-CH070]
        MACHINE: [openvario-7-PQ070]
        #TARGET: [openvario-image-testing, openvario-image]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Update submodules
        run: git submodule update --init

      - name: Startup container
        run: docker run -d --name ovbuild --rm -v $(pwd):/workdir ghcr.io/openvario/ovbuild-container:main --workdir=/workdir
        
      - name: Debug Environment
        run: |
          id
          ls
          docker exec ovbuild ls
          
      #- name: Build images
      #  env:
      #    MACHINE: ${{ matrix.MACHINE }}
      #  run: |
      #    who
      #    docker run -it --rm -v $(pwd):/workdir ghcr.io/openvario/ovbuild-container:main --workdir=/workdir bitbake
      #    source openembedded-core/oe-init-build-env .
      #    bitbake openvario-image openvario-image-testing
