name: Build documentation
on: 
  workflow_dispatch:
  
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          pre_compile: "apk add librsvg && ls -alh figures/ && for i in figures/*.svg;do rsvg-convert -f pdf -o ${i%.*}.pdf $i;done"
          working_directory: doc/ug_openvario
          root_file: ug_ov.tex
