name: Build documentation
on: 
  workflow_dispatch:
  
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          pre_compile: "SVGs := $(shell find $(IMG) -name '*.svg' | cut -d '.' -f 1) && SVG2PDF=$(foreach x,$(SVGs),$(x).pdf) && convert $(SVG2PDF)"
          working_directory: doc/ug_openvario
          root_file: ug_ov.tex
